### ISSUE TITLE
Adicionar i18n

### ISSUE THREAD

**Issue by patrickmonteiro** [patrickmonteiro/quasar-speech-api#14]
Este projeto tem uma visibilidade grande, e muitos dos consumidores são estrangeiros.
Seria interessante implementar o **i18n** tanto para os textos, quanto a a escolha da linguagem padrão do navegador.
Além disso, existe um menu de "cadastro", onde são feitas algumas perguntas e o usuário responde por voz. Também seria interessante que essas mensagens fossem sintetizadas de acordo com o idioma escolhido no **i18n**

Idiomas necessários:
- pt-br 🇧🇷
- en-us 🇺🇸

**Comment by TiagoDanin** [comment]
Eu estou trabalhando nisso! 😄
